//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cachimboCrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno()
        {
            this.cita = new HashSet<cita>();
            this.valoracion = new HashSet<valoracion>();
        }
    
        public string usuarioAlumno { get; set; }
        public int codigoCarrera { get; set; }
        public string contraseñaAlumno { get; set; }
        public string nombreAlumno { get; set; }
        public string apellidoAlumno { get; set; }
        public string celularAlumno { get; set; }
        public string correoAlumno { get; set; }
        public string nivelAlumno { get; set; }
        public Nullable<int> creditoAlumno { get; set; }
    
        public virtual carrera carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cita> cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracion> valoracion { get; set; }
    }
}
